
name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Chechout repository
        uses: actions/checkout@v4

      - name: Add itti-infra-share profile credentials to ~/.aws/credentials.
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile itti-infra-share
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile itti-infra-share
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.TEST_ROLE_TO_ASSUME }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{secrets.TEST_ROLE_TO_ASSUME}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build, tag, and push image to Amazon ECR  
        id: build-image
        env:
          TAG: ${{github.sha}}
        run: |
          docker build -t ${{secrets.TEST_AWS_REGISTRY}}/${{vars.REPOSITORY}}:$TAG .
          docker push ${{secrets.TEST_AWS_REGISTRY}}/${{vars.REPOSITORY}}:$TAG
          